spring.application.name=SpringADS

spring.datasource.url=jdbc:h2:mem:SpringADS
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=A1r1j3w5!

# Habilita a interface web do H2
spring.h2.console.enabled=true